export const TREATMENT_LIST_REQUEST = 'TREATMENT_LIST_REQUEST'
export const TREATMENT_LIST_SUCCESS = 'TREATMENT_LIST_SUCCESS'
export const TREATMENT_LIST_FAIL = 'TREATMENT_LIST_FAIL'

export const TREATMENT_DETAILS_REQUEST = 'TREATMENT_DETAILS_REQUEST'
export const TREATMENT_DETAILS_SUCCESS = 'TREATMENT_DETAILS_SUCCESS'
export const TREATMENT_DETAILS_FAIL = 'TREATMENT_DETAILS_FAIL'

export const TREATMENT_DELETE_REQUEST = 'TREATMENT_DELETE_REQUEST'
export const TREATMENT_DELETE_SUCCESS = 'TREATMENT_DELETE_SUCCESS'
export const TREATMENT_DELETE_FAIL = 'TREATMENT_DELETE_FAIL'

export const TREATMENT_CREATE_REQUEST = 'TREATMENT_CREATE_REQUEST'
export const TREATMENT_CREATE_SUCCESS = 'TREATMENT_CREATE_SUCCESS'
export const TREATMENT_CREATE_FAIL = 'TREATMENT_CREATE_FAIL'
export const TREATMENT_CREATE_RESET = 'TREATMENT_CREATE_RESET'

export const TREATMENT_UPDATE_REQUEST = 'TREATMENT_UPDATE_REQUEST'
export const TREATMENT_UPDATE_SUCCESS = 'TREATMENT_UPDATE_SUCCESS'
export const TREATMENT_UPDATE_FAIL = 'TREATMENT_UPDATE_FAIL'
export const TREATMENT_UPDATE_RESET = 'TREATMENT_UPDATE_RESET'

export const TREATMENT_CREATE_REVIEW_REQUEST = 'TREATMENT_CREATE_REVIEW_REQUEST'
export const TREATMENT_CREATE_REVIEW_SUCCESS = 'TREATMENT_CREATE_REVIEW_SUCCESS'
export const TREATMENT_CREATE_REVIEW_FAIL = 'TREATMENT_CREATE_REVIEW_FAIL'
export const TREATMENT_CREATE_REVIEW_RESET = 'TREATMENT_CREATE_REVIEW_RESET'

export const TREATMENT_TOP_REQUEST = 'TREATMENT_TOP_REQUEST'
export const TREATMENT_TOP_SUCCESS = 'TREATMENT_TOP_SUCCESS'
export const TREATMENT_TOP_FAIL = 'TREATMENT_TOP_FAIL'
